apps/crud/models.py
from crud import db

class ToDoInfo(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(20), unique=True, nullable=False)
    description = db.Column(db.Text(), unique=True, nullable=False)

    def __repr__(self):
        return '%r' % self.user_name

apps/crud/views.py
from flask import flash, redirect, render_template, request,Blueprint
from .models import ToDoInfo
from crud import db
from flask_login import login_required


crud_views = Blueprint('crud_views', __name__)

@crud_views.route('/')
def home():
    user_data = ToDoInfo.query.all()
    return render_template('crud/home.html',user_data=user_data)

@crud_views.route('/create',methods=["POST"])
@login_required
def create():
    tl = request.form.get('title')
    ds = request.form.get('description')

    if tl != '' and ds != '':
        try:
            todo_info = ToDoInfo(title=tl, description=ds)
            db.session.add(todo_info)
            db.session.commit()
            flash("Data submited successfully!!", "success")
        except Exception as e:
            print(e)
            flash("Title or description already exist!!!", "danger")
        return redirect('/')
    else:
        flash("Title or description may not blank!!!", "danger")
        return redirect('/')

@crud_views.route('/edit/<int:id>',methods=["GET",'POST'])
@login_required
def edit(id):
    todo_info = ToDoInfo.query.get(id)
    if request.method == 'POST':
        tl = request.form.get('title')
        ds = request.form.get('description')
        todo_info.title=tl
        todo_info.description=ds
        db.session.commit()
        flash("Data updated successfully!!", "success")
        return redirect('/')
    else:
        if todo_info is None:
            flash("Data Not found!!", "danger")
            return redirect('/')
        return render_template('crud/edit.html',data=todo_info)

@crud_views.route('/delete/<int:id>',methods=["GET"])
@login_required
def delete(id):
    todo_info = ToDoInfo.query.get(id)
    if todo_info is None:
        flash("Data Not found!!", "danger")
        return redirect('/')
    else:
        db.session.delete(todo_info)
        db.session.commit()
        flash("Data deleted successfully!!", "success")
        return redirect('/')

templates/crud/edit.html
{% extends 'base.html' %}

{% block title %}
Edit
{% endblock %}

{% block content %}

<div class="modal-body">
    <div class="modal-content container-fluid py-2">
    <h5 class="text-center alert alert-info">Edit Data</h5>
    <form action="{{url_for('crud_views.edit',id=data.id)}}" method='post'>
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <div class="mb-3">
            <div class="mb-3">
              <label for="Title" class="form-label">Title</label>
              <input type="text" class="form-control" name="title" required value="{{data.title}}">
            </div>
          <label for="Description" class="form-label">Description</label>
          <input type="text" class="form-control" name="description" required value="{{data.description}}">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

</div>

{% endblock %}

templates/crud/home.html
{% extends 'base.html' %}

{% block title %}
    Home Page
{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-4">
            <form action="/create" method='post'>
              <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                <div class="mb-3">
                    <div class="mb-3">
                      <label for="Title" class="form-label">Title</label>
                      <input type="text" class="form-control" name="title" required>
                    </div>
                  <label for="Description" class="form-label">Description</label>
                  <textarea class="form-control" name="description" rows="3" required></textarea>
                </div>

              <button type="submit" class="btn btn-primary">Submit</button>
              </form>
        </div>
    
        <div class="col-sm-8">
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Title</th>
                    <th scope="col">Description</th>
                    <th scope="col">Action</th>
                  </tr>
                </thead>
                <tbody>
                  {% for data in user_data %}
                    <tr>
                      <th scope="row">{{data.id}}</th>
                      <td>{{data.title}}</td>
                      <td>{{data.description}}</td>
                      <td>
                        <a class="btn btn-info btn-sm" href="{{ url_for('crud_views.edit',id=data.id) }}">Edit</a>
                        <a class="btn btn-danger btn-sm" href="{{ url_for('crud_views.delete',id=data.id) }}">Delete</a>
                      </td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
        </div>
    </div>
</div>

{% endblock %}