apps/authentication/views.py
from flask import Blueprint, flash, redirect, render_template,url_for,request
from flask_login import login_user,login_required,logout_user,current_user
from .models import User
from crud import db,login_manager,mail
from .forms import LoginForm,RegisterForm,PasswordChangeForm,PasswordResetForm
import random
import string
from flask_mail import Message
from ..user_profile.models import Profile


auth_views = Blueprint('auth_views', __name__)

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

@auth_views.route("/register", methods=("GET", "POST"))
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        try:
            email = form.email.data
            username = form.username.data
            password = form.password.data
            
            newuser = User(
                username=username,
                email=email,
            )
            newuser.set_password(password)
            db.session.add(newuser)
            db.session.commit()
            user_profile = Profile(user_id = newuser.id,first_name = username)
            db.session.add(user_profile)
            db.session.commit()
            flash(f"Account Succesfully created", "success")
            return redirect(url_for("auth_views.login"))

        except Exception as e:
            print(e)
            pass

    return render_template("authentication/auth.html",form=form)

@auth_views.route("/login", methods=("GET", "POST"))
def login():
    form = LoginForm()

    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data.encode('utf-8')
        try:
            user = User.query.filter_by(email=email).first()
            if user and user.check_password(password):
                login_user(user)
                user.login_timestamp_update()
                flash("Login successfully!!!", "success") 
                return redirect(url_for('crud_views.home'))
            flash("Invalid Username or password!", "danger")
        except Exception as e:
            print(e)
            pass

    return render_template("authentication/auth.html",form=form)

@auth_views.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('crud_views.home'))

@auth_views.route("/change_password", methods=("GET", "POST"))
@login_required
def change_password():
    form = PasswordChangeForm()
    if form.validate_on_submit():
        user = current_user
        cur_pass = form.current_password.data
        new_pass = form.confirm_new_password.data
        if user.check_password(cur_pass.encode('utf-8')):
            if new_pass != cur_pass:
                user.set_password(new_pass)
                db.session.commit()
                flash("Password change successfully", "success")
            else:
                flash("Current password and new password must not be same!!", "danger")
        else:
            flash("Invalid current password!!", "danger")
    return render_template("authentication/change_password.html",form=form)

@auth_views.route('/reset_password',methods=["POST","GET"])
def reset_password():
    if request.method=="POST":
        email = request.form['mail']
        user = User.query.filter_by(email=email).first()

        if user:
            hashCode = ''.join(random.choices(string.ascii_letters + string.digits, k=24))
            user.hash_string = hashCode
            db.session.commit()

            msg = Message('Confirm Password Change',recipients = [email])
            msg.body = f"Hello {user.username},\nWe've received a request to reset your password. If you want to reset your password, click the link below and enter your new password\n" + request.host + url_for('auth_views.reset_password_validate',user_id=user.id,hashCode=user.hash_string)
            mail.send(msg)
            flash(f"We have sent password reset link in {email}..Please check your email and reset your password!!", "success")
        else:
            flash("Invalid email address!!", "danger")   
    return render_template("authentication/reset_password.html")


@auth_views.route("/reset_password/<int:user_id>/<string:hashCode>",methods=["GET","POST"])
def reset_password_validate(user_id,hashCode):
    user = User.query.filter_by(id = user_id,hash_string = hashCode).first()
    if user:
        form = PasswordResetForm()

        if form.validate_on_submit():
            new_pass = form.confirm_new_password.data
            user.set_password(new_pass)
            user.hash_string= None
            db.session.commit()
            flash("Password reset successfully", "success")
            logout_user()
            return redirect(url_for('auth_views.login'))
        else:
            return render_template("authentication/change_password.html",form=form)
    else:
        flash('Link is invalid or expired!!!!',"danger")
        return redirect(url_for('auth_views.reset_password'))

apps/user_profile/views.py
import os
from flask import Blueprint, flash, render_template,request,send_from_directory
from flask_login import login_required,current_user
from .models import Profile,Song
from crud import db,app,ALLOWED_EXTENSIONS
from .forms import ProfileForm
from werkzeug.utils import secure_filename

profile_views = Blueprint('profile_views', __name__)

def save_image(file):
    filename = secure_filename(file.filename)
    file.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))
    return filename

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@app.route('/media/<path:filename>')
def media(filename):
    return send_from_directory(
        app.config['UPLOAD_FOLDER'],
        filename,
        as_attachment=True
    )

@profile_views.route("/user_profile", methods=("GET", "POST"))
@login_required
def user_profile():
    form = ProfileForm()
    current_profile = Profile.query.filter_by(user_id=current_user.id).first()
    if form.validate_on_submit():
        try:
            file = form.profile_image.data
            orgnl_file = request.files['profile_image']
            if file and allowed_file(orgnl_file.filename):
                filename = save_image(orgnl_file)
                current_profile.profile_image = filename
            current_profile.first_name = form.first_name.data
            current_profile.last_name = form.last_name.data
            current_profile.age = form.age.data
            current_profile.gender = form.gender.data
            current_profile.favourite_song.append(int(form.favourite_songs.data[0]))
            db.session.add(current_profile)
            db.session.commit()
            flash("Profile updated successfully!!", "success")
        except Exception as e:
            print(e)
            pass

    return render_template("profile/my_profile.html",form=form,pf_data=current_profile)

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} CRUD APP {% endblock %}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="/"><b>My App</b></a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/">Home</a>
            </li>
            {% if current_user.is_authenticated %}

            <li class="nav-item">
              <div class="dropdown">
                <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Action
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <a class="dropdown-item" href="{{url_for('auth_views.change_password')}}">Change Password</a>
                  <a class="dropdown-item" href="{{url_for('profile_views.user_profile')}}">My Profile</a>
                  <a class="dropdown-item text-danger" href="{{url_for('auth_views.logout')}}">Logout</a>
                </div>
              </div>
            </li>

            <li class="nav-item">
              
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{url_for('auth_views.login')}}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{url_for('auth_views.register')}}">Register</a>
            </li>
            {% endif %}
          </ul>
        </div>
        <form class="d-flex">
          <input
            class="form-control me-1"
            type="search"
            placeholder="Search"
            aria-label="Search"
          />
        </form>
      </div>
    </nav>
    <br />

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category,message in messages %}
    <div class="alert alert-{{category}} border-dark mx-2" role="alert">
      {{message}}
    </div>
    {% endfor %} {% endif %} {% endwith %} {% block content %} {% endblock %}

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>